name: Build and Publish NuGet Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_NUGETVERSIONV2"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build and pack
        run: dotnet pack -c Debug --version-suffix $GITVERSION_NUGETVERSIONV2 Google.Ads.GoogleAds.Core/src/Google.Ads.GoogleAds.Core.csproj

      - name: Publish NuGet package
        run: dotnet nuget push -s https://nuget.nwcloudsolutions.com/v3/index.json -k ${{ secrets.NUGET_API_KEY }} **/*.nupkg